name: Residence Automatic Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    if: contains(github.event.head_commit.message, '[Build Skip]') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Convert project to Maven
      run: |
        chmod +x converter.sh
        ./converter.sh

    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: Residence
        path: target/Residence.jar
        
